"""create tables Secret, SecretKey, SecretCode

Revision ID: 823cfeb70e58
Revises: 
Create Date: 2021-11-03 17:06:48.269849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '823cfeb70e58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default='11/03/2021, 20:06:47', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secretcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('secret', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['secret'], ['secret.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('secretkey',
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('secret', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['secret'], ['secret.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secretkey')
    op.drop_table('secretcode')
    op.drop_table('secret')
    # ### end Alembic commands ###
